[project]
name = "ghostwire-refractory"
version = "0.1.0"
description = "A neural lattice forged in neon, whispering through the data fog"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anyio>=4.11.0",
    "apsw>=3.50.4.0",
    "asyncio>=4.0.0",
    "fastapi>=0.119.0",
    "hnswlib>=0.8.0",
    "httpx[http2]>=0.28.1",
    "langchain>=0.3.27",
    "langchain-community>=0.3.31",
    "langchain-openai>=0.3.35",
    "numpy>=2.3.3",
    "ollama>=0.6.0",
    "openai>=2.3.0",
    "psutil>=7.1.0",
    "pydantic>=2.12.0",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pytest-sugar>=1.1.1",
    "pytest-tornasync>=0.6.0.post2",
    "pytest-trio>=0.8.0",
    "pytest-twisted>=1.14.3",
    "qdrant-client>=1.15.1",
    "rouge>=1.0.1",
    "rouge-metric>=1.0.1",
    "rouge-score>=0.1.2",
    "sentence-transformers>=5.1.1",
    "tiktoken>=0.12.0",
    "twisted>=25.5.0",
    "typing>=3.10.0.0",
    "uvicorn>=0.37.0",
    "vectorlite-py>=0.2.0",
]

[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ghostwire-refractory"]

[tool.ruff]

[tool.ruff.lint]
select = ["I"]
